include: package:flutter_lints/flutter.yaml
analyzer:
  language:
    strict-raw-types: true
    strict-casts: true
    # plugins:
  #   - custom_lint
  exclude:
    - "example/**"
    - "build/**"
  errors:
    invalid_override_of_non_virtual_member: error
    unused_import: warning
linter:
  rules:
